CREATE DATABASE twitter;

CREATE TABLE Users(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE Tweets(
    id SERIAL PRIMARY KEY,
    uid INTEGER REFERENCES Users(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    created_at DATE NOT NULL
);

CREATE TABLE Followers(
    did INTEGER REFERENCES Users(id) ON DELETE CASCADE,
    tid INTEGER REFERENCES Users(id) ON DELETE CASCADE
);

ALTER TABLE Users ADD COLUMN session_id TEXT;
ALTER TABLE Users ADD COLUMN password TEXT;
ALTER TABLE Users ADD CONSTRAINT unique_name UNIQUE (name);
ALTER TABLE Tweets ALTER COLUMN created_at TYPE TIMESTAMP, ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
